# Generated by Django 4.0.2 on 2022-02-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_generator', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
