# Generated by Django 4.0.2 on 2022-02-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_generator', '0003_resume_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user_id',
        ),
    ]
